### ISSUE TITLE
User Story: Like / Unlike

### ISSUE THREAD

**Issue by IuliiaKonovalova** [IuliiaKonovalova/django-blog#7]
As a **Ste User** I can **like or unlike a post** so that **I can interact with the content**.

**Comment by Krish-bhardwaj** [comment]
Hi i am a fresher looking for some opensource contribution can u help me out i want to contribute to your project and can u assign me this issue:)

**Comment by IuliiaKonovalova** [comment]
> Hi i am a fresher looking for some opensource contribution can u help me out i want to contribute to your project and can u assign me this issue:)

Hi Krish, Thanks for your interest, but this is a code along project from my Institute)
